Packer base
Otus-DevOps-2018-05/Hravn_infra pull request #7
Opened 2018-07-02 13:33 UTC by Hravn

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Описанно в ридми

## Как проверить работоспособность:
 -  Описанно в ридми 

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2018-07-02 18:22 UTC, Nklya requested changes
Добрый вечер.

Владимир, в данный момент есть пару проблем, которые нужно пофиксить:
1. Падающие проверки тревиса из-за кривого variables.json.example
2. Шаблон должен называться immutable.json, а не immutables.json.
3. proj_id и src_img в шаблонах должны быть обязательны, т.е. в шаблоне равны null
4. Скрипты из прошлого ДЗ должны были переносится в папку config-scripts, а не удалятся
5. Дописать хоть что-то осмысленное в ридми

2018-07-02 18:22 UTC, Nklya commented on install_mongodb.sh
> -#!/bin/bash
Скрипты должны были переносится в папку  config-scripts, а не удалятся

2018-07-02 18:22 UTC, Nklya commented on packer/immutables.json
> +        "src_img" : "ubuntu-1604-lts",
proj_id и src_img должны быть обязательны, т.е. в шаблоне равны null

2018-07-02 18:22 UTC, Nklya commented on packer/ubuntu16.json
> +        "src_img" : "ubuntu-1604-lts",
proj_id и src_img должны быть обязательны, т.е. в шаблоне равны null

2018-07-02 18:22 UTC, Nklya commented on packer/variables.json.example
> +	"src_img": "ubuntu-1604-lts"
Во-первых, здесь кривое форматирование

2018-07-02 18:22 UTC, Nklya commented on README.md
> +gcloud compute instances create reddit-app-full \
В ридми стоит писать что-то более осмысленное о том, что сделано в ДЗ.
И использовать форматирование https://guides.github.com/features/mastering-markdown/

2018-07-02 18:22 UTC, Nklya commented on packer/variables.json.example
> +    "tags": ["redis","packer"]
Во-вторых, таким образом переменные передавать нельзя в пакере. Поэтому тревис падает.
Вот ишью на эту тему https://github.com/hashicorp/packer/issues/2278.

Судя по всему работает такой вариант: ` "tags": "redis, packer"`

2018-07-02 18:22 UTC, Nklya commented on packer/immutables.json
> +{
Шаблон должен называться immutable.json, а не immutables.json.

2018-07-02 18:22 UTC, Nklya commented on packer/immutables.json
> +            "execute_command": "sudo {{.Path}}"
В этом шаблоне в качестве базового образа можно использовать reddit-base, чтобы не ставить опять руби и монгу.

2018-07-03 09:45 UTC, Hravn commented
Поправил.

2018-07-03 14:43 UTC, Nklya approved these changes
Добрый вечер.

Владимир, условия ДЗ выполнены, все сделано относительно ок 👍 

В следующих ДЗ ридми нужно оформлять нормально.

2018-07-03 14:43 UTC, Nklya commented on README.md
> +Для работы с packer не всё необходимое находится в директории ./packer
Опять-таки опять в ридми в каждом ДЗ стирается все что сделано раньше.
Вот простой пример нормального оформления.
https://github.com/Otus-DevOps-2018-05/RenderQwerty_infra/blob/master/README.md

2018-07-03 14:43 UTC, Nklya commented on packer/variables.json.example
> +	"src_img": "ubuntu-1604-lts",
Тут кривое форматирование осталось

2018-07-03 14:43 UTC, Nklya commented
Ну и конфликты нужно перед мержем пофиксить

<img width="687" alt="image" src="https://user-images.githubusercontent.com/26086394/42226827-9d6a2838-7ee8-11e8-9694-9ac20c53fcc8.png">

2018-07-03 18:59 UTC, merged